### ISSUE TITLE
Divisão dos dados

### ISSUE THREAD

**Issue by soareswallace** [RomeroBarata/IF702-redes-neurais#1]
`## Treino: 50%, Validação: 25%, Teste: 25%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/4, 
                                                    random_state=42, stratify=y)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=1/3, 
                                                  random_state=42, stratify=y_train)`

Neste passo estou com esse erro. Já dei um procurada no google, mas nao entendi muito bem.

> The test_size = 0 should be greater or equal to the number of classes = 2

**Comment by RomeroBarata** [comment]
Qual data set você está usando @soareswallace?

**Comment by soareswallace** [comment]
Mamografia

**Comment by RomeroBarata** [comment]
Provavelmente você está utilizando Python 2. O ideal seria utilizar Python 3 (o código não foi testado para Python 2).

O que está acontecendo é que em Python 2 a expressão:
`1/4 == 0` 

Em Python 3:
`1/4 == 0.25`

Para corrigir isso, você pode modificar as seguintes partes do código:
`test_size=1./4.` e `test_size=1./3.`.
